services:
  bayer-wecom-mobile:
    build:
      context: .
      dockerfile: Dockerfile.static
    image: bayer-wecom-mobile:static
    container_name: bayer-wecom-mobile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - shared-proxy

networks:
  shared-proxy:
    external: true
