# 将此 location 块添加到服务器已有 Nginx 配置的 server {} 中
# 与 cn-ph-bidding-process 的 Nginx 放在同一个 server 下面即可

location /bayer-mobile/ {
    proxy_pass http://bayer-wecom-mobile/bayer-mobile/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
}
